apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn # This is the default SC created by the Helm chart
  resources:
    requests:
      storage: 1Gi
