cloudflare_api_token: ENC[AES256_GCM,data:a0oIg65C9lGUD8txG8wlVujGF1LPzuIVFrSerdEIVHZhtUkbUTizxkq6VxtBj2vj9ocSXek=,iv:iI3d2behFcIY6Z6E+TV3weIwrr4JfJohVCkQvRNu+Kc=,tag:k92KO/Hi7WLpyYQ2tk774Q==,type:str]
hcloud_api_token: ENC[AES256_GCM,data:DV+RDfGFsdNcRtrTEmPIC9aiz+btfLb+qHtoKm4gXA55Fg2Ko+Imn3R9X9m534IEeiRDAhtf5Sr25/Ebb9Jeaw==,iv:r3qhY41U1to7osV1My4w/2QuooFAfKzYiDJGZoMPbTc=,tag:weY+AaG3Gyf4yf0IOvVebA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTDlBMlZ3ZjZUa2YvNUFI
            eVBERXhYZFZyQVVqM2Q1cVB0KzhjSEVUQ0QwClI4WkxVdTVyODFHRWhjREdjQXdm
            UjR4OWNNSTJ1MG5ndlZkeGEvTWhjbVUKLS0tIEtzMWh6VlVkSER4MEJRODJvcXo1
            ZzNUZ0FyWVdtWURRY1FaS1AvMnNFdHcKEeLLyWLAbLgwOqp5/GzhhdmcCqhTzcr5
            JhPf4KFmkZx0H8rYc0BdUvjFyV+xwgo353D3zjWax+O175p7JOuqhA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1chvcefkzfesskrs2vf7sp9fjktpx5z8qc4ggksuwfn483fwpjvxsv88jpa
    lastmodified: "2026-09-10T20:25:13Z"
    mac: ENC[AES256_GCM,data:wjoNxBRhuGdeyfjT9bo/IhnBhxaitAW1Tuf7tawfvtHahi2uImNWBVbcR8q8whiiV9ckqVS04PjOYAqiC6bgbv8PTasg7GO+7hiXs/M78Ay3wIysiqA/NUI5X4whCw3PaSQMjZ9fRXsUxwwFBbmmDdQ5fU+vO/XC820X7QNqBJY=,iv:VnhF38Z+3W9Yf5Nt2SdIOdPGldHlx6J9q61zABLARTk=,tag:dG5SkrY49cTF1XUjaE9UZg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
