{
  lib,
  pkgs,
  config,
  ...
}:

let
  # A helper to easily access the sops templates configuration.
  cfg = config.sops.templates;
in
{
  # This block adds the new `attrSet` and `toFile` options to the
  # existing `sops.templates.<name>` submodule.
  options.sops.templates = lib.mapAttrs (
    _: template: {

      attrSet = lib.mkOption {
        type = lib.types.nullOr lib.types.attrs;
        default = null;
        description = lib.mdDoc ''
          An attribute set holding the data for the template.
          This will be passed to the `toFile` function to generate the final file content.
          This option cannot be used at the same time as `content` or `path`.
        '';
      };

      toFile = lib.mkOption {
        # The function must take an attrset and return a derivation (a file path).
        type = lib.types.nullOr (lib.types.functionTo lib.types.package);
        default = null;
        description = lib.mdDoc ''
          A function that takes `attrSet` and returns a file derivation.
          The function receives the `attrSet` option as its only argument.
          This is commonly used with Nixpkgs' format generators, like `pkgs.formats.json.generate`.
        '';
        example = lib.literalExpression ''
          data: pkgs.formats.toml.generate "config.toml" data
        '';
      };

      # This block adds assertions to ensure the new options are used correctly.
      config = lib.mkIf (template.attrSet != null) {
        assertions = [
          {
            assertion = template.toFile != null;
            message = "When using `attrSet`, the `toFile` option must also be defined for sops.templates.${template.name}.";
          }
          {
            assertion = template.content == null;
            message = "`attrSet` cannot be used with `content` for sops.templates.${template.name}.";
          }
          # A conflict with `path` is implicitly handled, as this module sets `content`,
          # and sops-nix already asserts that `content` and `path` cannot co-exist.
        ];
      };
    }
  );

  # This block generates the configuration. It iterates over all defined sops templates.
  # If a template uses `attrSet` and `toFile`, it generates the file content.
  config = lib.mkMerge [
    (lib.mapAttrs' (
      name: template:
      # Create a config snippet for each template that uses the new options.
      lib.nameValuePair "sops" {
        templates."${name}" = lib.mkIf (template.attrSet != null && template.toFile != null) {
          # Set the `content` option to the path of the file generated by the `toFile` function.
          # sops-nix will then use this generated content for the final secret file.
          file = template.toFile template.attrSet;
        };
      }
    ) cfg)
  ];
}
