secrets:
    newt: ENC[AES256_GCM,data:TG7YLNwn40DErPJvQ6NIxz9rRC0lQrQbNzavAXItWxOriuL4GyEPWvr9vcT+9Lb7,iv:bHo9krLI6onX83e0XLkraNSM7vCQZM0JBTFwfhwyUjw=,tag:APZiwlfBFooqqs/ckRuS3w==,type:str]
    bitmagnet_postgres_password: ENC[AES256_GCM,data:4aVfW/7CyMx0iNJZRPuIEQbzbC8hN61Y,iv:RARLK3Utkyj93i6LhMwJbHEguHvE0XBM+2C02Mc3OGI=,tag:fmseQvR9gxJH89M4/JAiYQ==,type:str]
    airvpn_wireguard_private_key: ENC[AES256_GCM,data:zBQSNhskohNoZKzGOUDpHLyZ1Jx1pg2izVRrL/VfDKFnPdNmWj/JOUmg/kI=,iv:FJo61MWNle4sslS+Ra+6d/7+3if/DAujOc1EOzpPmjc=,tag:6k1FNdcZZ0qbNfLB8/kA9w==,type:str]
    airvpn_wireguard_preshared_key: ENC[AES256_GCM,data:VBzWhnvURL3X+EiUXn1Sak3ICSPuXYYG4/NeV2nB/rNnTPC4kJoMWDsK7z8=,iv:wOkF6scjziPUvcenGGabh1DkWfV6CcJUkSdSaZ9ebxM=,tag:wscby9aWuqNQqPsVjn9OGA==,type:str]
    tmdb_api_key: ENC[AES256_GCM,data:PYOEnAASGY2zlOPylzQf3ZJRVsZITj70qu7USWek6cQ=,iv:O3NgE8yIYQzOoPfv8fFFTydVJt4Vy9BioWacJSmhI+c=,tag:HiKOmyDa3W7yixCxhNxTow==,type:str]
    pocketid_encryption_key: ENC[AES256_GCM,data:Y8TxDXCfJ2kbpT5jh6DZ445JJbVPy/fWfKdL3UwbG3FHNff5D+PklXZHn8s=,iv:64ju6TrI5CAulMrzbHSlOZrHQUdw60aHZoAZiQOzLR4=,tag:qtehIaZBhC32i+SFuw4AUw==,type:str]
    maxmind_license_key: ENC[AES256_GCM,data:KWY6AfT7ia1AHt/PeZfLX2JbepBhF0Vz+7lGefIYi/yqpo7xrVSKYw==,iv:ebTfxyUa1q4igRDEK4i2vAXIxu5q8yVVHYe3BUPIMsQ=,tag:/WLCfMMkEFQd/2Jtw0a7JQ==,type:str]
sops:
    age:
        - recipient: age1chvcefkzfesskrs2vf7sp9fjktpx5z8qc4ggksuwfn483fwpjvxsv88jpa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhY1ZJak14Wno4WnZXMkMr
            eEVVL1R1UU0rMkhFRXRUSmZPQnpWb0RuTTNnCkNIaW9QN1QyWGRiYmtaL3FXYXVQ
            ajQvTklkZ1pQT2F6SDlnQlc1cCszamMKLS0tIHA2bUtIVHlUUHQ2d0xWdWtIVys4
            WnlNWkFUeU5iS2tlK0lISFR1WWVWejQKnC0OyfvgX9liHnJorlAQLuVNTosyGrhN
            kK0EeBCCNdWqK/uiG9S2SJ0vyqdhPReukI9I2VpLGHbfJ2CpYRCbQw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tsfvlywtu7c9aux8y9efscqak3nvmz85zanyv5q2qvwthphf5u7qa499tl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkd2dEWVo1M1h4bXNpOFVJ
            M2swSGs0c1crTXdmYXJjdFF5UFE0dEl1K1ZFClYycDBoZGRMT1N5WlZ3SzRoYnBU
            NFkwZnQxMGpuUndSRlAycEJZazJ6U3MKLS0tIGNrWm8zSlAwdkcxWERETzI4cE53
            VE05VDJPazcwNCsxZFdGaEZObndDRTQKuQpAbiS160krszlCpHj5CruqYKbe1caV
            Sv6QuZksClvH8e/tC30isnR0hkriuJfGVkywGLPn9TCCMetSfCb7Hg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mslxutmqu56fhl0rgk7flysyacyxks3evnmfckzzykh3wcvzc5tqx9q6dd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrL3J4Qm9sdTVlZ3c1T0Q2
            elY0YVBrdmhsSW9nc2xob2pNcWtDdU9HUUNZClFvemJsSm1iVS9pOXZwZTFubHpL
            Z3NjTVE1Sjgwd3FlTzMwS1RwYlcycEkKLS0tIC9VakMzK3pGRytoOGlsVFpEcVVE
            Sk5USWt1U3R0OW9XQWJ6emcvWGZkTmMK3iFhXptJNYPHlBZg3ac2u5NxA8F4NuHS
            EcQV6CrsaiCDP45+crRmsxV4g79ozyt+DnVlRO7cT8yCxdp0IfNJSA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lg4e7rxq944fezdtqsrrhjzxarq2f5e0a804juyrrhdynkxmqg9qlkadk7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5d1BUNnB6M014Nk9hZ2cy
            Q1g3ejFVV0w2c244bXo0TGd5QXJ0Q0J4ZkRBCnJHQTBUeHJObUh1VW8vaC8weHNh
            WjNFZGgwZlcyNk9STFRvZHJNWUJua0UKLS0tIDNpSmZsWUVqWDhpOGFzSEZUMFkx
            OW1GY3llZFRzMzgwbGk4YW5lVllLRmcKjwz5ntlBRTXNrWXHbHC7I1UQTJCgF2KU
            fZ6doG/77GNUVAEVSb4CnEmbbPPwQ7AQK4JiPoz2RAWuTIhuVNTS7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T19:50:40Z"
    mac: ENC[AES256_GCM,data:l63nygtBEC5xytDedhTJ1EJGs4fpqXEs3K+JcZFQTBLQIsYr1FcUs+g09Xuo6fOc6xf2xzsQL0KSF1l4Ph0oAWKkmcDItleh1UfljmbyQeSYRbK1Wtunym6Ymd4FwSnE7LujJgVrPpTuuNuoTjy4CCht1+67sP9+I1r6Ndw6gdE=,iv:zfgDi16vX4+xBzss6+SSDZoP7c4eamjucFFZlfMz4fQ=,tag:sz+qlhOOr6JsXsAByNmk3w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
