secrets:
    newt: ENC[AES256_GCM,data:TG7YLNwn40DErPJvQ6NIxz9rRC0lQrQbNzavAXItWxOriuL4GyEPWvr9vcT+9Lb7,iv:bHo9krLI6onX83e0XLkraNSM7vCQZM0JBTFwfhwyUjw=,tag:APZiwlfBFooqqs/ckRuS3w==,type:str]
    bitmagnet_postgres_password: ENC[AES256_GCM,data:4aVfW/7CyMx0iNJZRPuIEQbzbC8hN61Y,iv:RARLK3Utkyj93i6LhMwJbHEguHvE0XBM+2C02Mc3OGI=,tag:fmseQvR9gxJH89M4/JAiYQ==,type:str]
    airvpn_wireguard_private_key: ENC[AES256_GCM,data:zBQSNhskohNoZKzGOUDpHLyZ1Jx1pg2izVRrL/VfDKFnPdNmWj/JOUmg/kI=,iv:FJo61MWNle4sslS+Ra+6d/7+3if/DAujOc1EOzpPmjc=,tag:6k1FNdcZZ0qbNfLB8/kA9w==,type:str]
    airvpn_wireguard_preshared_key: ENC[AES256_GCM,data:VBzWhnvURL3X+EiUXn1Sak3ICSPuXYYG4/NeV2nB/rNnTPC4kJoMWDsK7z8=,iv:wOkF6scjziPUvcenGGabh1DkWfV6CcJUkSdSaZ9ebxM=,tag:wscby9aWuqNQqPsVjn9OGA==,type:str]
    tmdb_api_key: ENC[AES256_GCM,data:PYOEnAASGY2zlOPylzQf3ZJRVsZITj70qu7USWek6cQ=,iv:O3NgE8yIYQzOoPfv8fFFTydVJt4Vy9BioWacJSmhI+c=,tag:HiKOmyDa3W7yixCxhNxTow==,type:str]
    pocketid_encryption_key: ENC[AES256_GCM,data:Y8TxDXCfJ2kbpT5jh6DZ445JJbVPy/fWfKdL3UwbG3FHNff5D+PklXZHn8s=,iv:64ju6TrI5CAulMrzbHSlOZrHQUdw60aHZoAZiQOzLR4=,tag:qtehIaZBhC32i+SFuw4AUw==,type:str]
    maxmind_license_key: ENC[AES256_GCM,data:KWY6AfT7ia1AHt/PeZfLX2JbepBhF0Vz+7lGefIYi/yqpo7xrVSKYw==,iv:ebTfxyUa1q4igRDEK4i2vAXIxu5q8yVVHYe3BUPIMsQ=,tag:/WLCfMMkEFQd/2Jtw0a7JQ==,type:str]
    qui_oidc_client_secret: ENC[AES256_GCM,data:IFkNKv0ggPP1oNzixd/GdFfGfU29uXRKdtc1LnC37/Y=,iv:YC3eoLgcDWdG7GgOSOYIYdbl0MKgCDXB8CTWcFfYbD0=,tag:velgKqqpqK+cDaEWTHTPqQ==,type:str]
sops:
    age:
        - recipient: age1chvcefkzfesskrs2vf7sp9fjktpx5z8qc4ggksuwfn483fwpjvxsv88jpa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaFZ1TGplZno5ZE9CSjBC
            QWRaU1ZIUnV5MWo4QUlWeEwxeVBpaDlkOVNVCmNpUXlLY2FGMmdBaVJ4UVc0T0ww
            SjBWYThvQVBpV0lxa1VRZGZZa1FKcncKLS0tIEFsM2dVZlVNR0E3NVNFSkdmLzZI
            cGhHOXhBT1c2eTZaT3VOelMySW14ZlUKBu7LIZkS/ZZueNBzxkImqPfZXYps48+u
            5VBRfwjTuDoCgC0tPGiTtrIWjsCMMMBLHDNhklAuju+65g/DkWzALg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T22:16:10Z"
    mac: ENC[AES256_GCM,data:vxpL74x2s4WHF3OQ3tFABWTbcWUVepps0ROjOEjackd96nK+f+Za4arabo9R5wmaP8IZGClmKlUJ7psFSMoOhuA4e7jSY80wFDr7jcz6Ok4qte3+2K7Kco7uf2dc117ZMhRZSk8RsMqNatYnr3oS5m084EQlw5hjcK2iPG6n06g=,iv:pbC153XPKQBJNnmHxQQVlkeIhIlk58Ttz6w3p0N/59Y=,tag:rCbnKg3k2zashGdoldH2PQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
