{...}: {
  imports = [
    ./atuin.nix
    ./ags
    ./bat.nix
    ./broot.nix
    ./btop.nix
    ./direnv.nix
    ./eza.nix
    ./firefox.nix
    ./git.nix
    ./kitty.nix
    ./mangohud.nix
    ./mpv.nix
    ./ripgrep.nix
    ./rofi
    ./starship.nix
    ./swaylock.nix
    ./tmux.nix
    ./vscodium.nix
    ./waybar
    ./wezterm.nix
    ./wlogout
    ./yazi.nix
    ./yt-dlp.nix
    ./zathura.nix
    ./zoxide.nix
  ];
}
