{...}: {
  imports = [
    ./ags
    ./atuin.nix
    ./bat
    ./broot.nix
    ./btop
    ./direnv.nix
    ./discord
    ./eza.nix
    ./firefox.nix
    ./git.nix
    ./hyprlock.nix
    ./kitty.nix
    ./lazygit.nix
    ./mangohud.nix
    ./mpv
    ./ripgrep.nix
    ./spotify.nix
    ./rofi
    ./rbw.nix
    ./starship.nix
    ./thunderbird.nix
    ./tmux.nix
    ./vscodium.nix
    ./waybar
    ./wezterm.nix
    ./wlogout
    ./yazi.nix
    ./yt-dlp.nix
    ./youtube-music.nix
    ./zathura.nix
    ./zoxide.nix
  ];
}
