#ENC[AES256_GCM,data:g0otgVIZq38j90Kjt6S3iZeb1j2pk41kh3CZX50bVB8Q3IN/7iFaCC3jQ58TLwYbwEiYqluK3kxwbaCHwCGYGbAeXcsTyA==,iv:Gg6mpYYJwKmlNAs1XFFyyDskhqBI05QZl7yoBYxLaLo=,tag:Qb+F+m2FOz2rCm0C5wXHGA==,type:comment]
#ENC[AES256_GCM,data:oIHxJ+l0/2Tqb2vmaSNul3hvlSpFkdkqChbzCt+Zu37vSgQSIVGOdfq5OVOzbc0JVDWUbd/b/tA=,iv:E5JSm9q9Om75gMtRrAwf2H0eepAZuqJHnBXhk/QwHnw=,tag:F1MeN3EvnmSQekrh0CPNpQ==,type:comment]
#ENC[AES256_GCM,data:2ZVbOOj698rAxU4LW5F6fTKJFG7us/kXWhlZ0styCX+zXRBQNs71uC7cWC2rFXL0vupRtza70PQwrvBjEea3OIo2whKWrpTBzs2QePU68gAHzK1PPKgJZw==,iv:Pe1JqtizxAW5U7qFkLe90UMMaM+PoKZFtFXeH6Q2cXQ=,tag:yyX2OBFnIpUUlkXm9jU9QA==,type:comment]
#ENC[AES256_GCM,data:LiQvJcWGKh1Lb8C7w9g4jYMucL1UDTLOE8on7JmLhGmYqiH6y2oDrmfssPtRBFOVeLv+/fBIP1+n+EMRivFF,iv:Viwtk2s+p7kXqiyAdMS3eWvvBcWAgntLv7nzvSd8j0c=,tag:5NlHD0CQLxbnQVH/ZdOl4g==,type:comment]
commands:
    dry_run: ENC[AES256_GCM,data:6GqjhHo=,iv:d5xh/3KgMEyEr1bY6Owtjw998J5Beyusb1J6s71wOhs=,tag:M37WN1Fk+5v3g89KK6aSjQ==,type:bool]
    cross_seed: ENC[AES256_GCM,data:TozL+oQ=,iv:x8VHeYySJD07S2sKhi+DTZRBdEEEKtYN71ZGOdEnHYw=,tag:c4Mh7f46Fb6kYHH4d3J8qg==,type:bool]
    recheck: ENC[AES256_GCM,data:TTP16G0=,iv:LlPqiDVZBMfnGHHMVBdudG+hNmKWksI717m+2mRq2tE=,tag:d7musXTf4HclzyCHzRVDUA==,type:bool]
    cat_update: ENC[AES256_GCM,data:C4QJ90E=,iv:Z3zS/D7l3rQ+1dQJMtRhAJJpfgl57OflTtOzVLHmRAI=,tag:MD/xbvC3hy7aw/FxkcVZZA==,type:bool]
    tag_update: ENC[AES256_GCM,data:29LsHQ==,iv:Hd4jEMuZorzkwO1zVvVt3HrfieVWM2TC0iWs3sBDyq4=,tag:G5DtSqguNnUQ8ljQ+mpT3A==,type:bool]
    rem_unregistered: ENC[AES256_GCM,data:8eAsMw==,iv:s4jC3nBbk7zEYlJc9WrM5auclFm8AOruAkVKTQDIWHg=,tag:vIRQCmu34bgMxDWDNOwqfw==,type:bool]
    tag_tracker_error: ENC[AES256_GCM,data:n6uSRA==,iv:wl8Kd3MfdGTftMvxa5YiDtvsmZxutUUZsKaUYzM9iIo=,tag:A8I9aFT/LiKnxyok9FUTzw==,type:bool]
    rem_orphaned: ENC[AES256_GCM,data:CJ+xlQ==,iv:SL07uoOvUD8axy3l1Ud8DkkC8XH7qpdlg7S/OZKclHc=,tag:m32GHXvWZgEhECih50cxBQ==,type:bool]
    tag_nohardlinks: ENC[AES256_GCM,data:GvnPLw==,iv:euhdmpJmLbmpb75opl46IqRVxFGCofz8bh/ikyYZPDU=,tag:Pa49TTCXTjsQ1nNC6NAvCg==,type:bool]
    share_limits: ENC[AES256_GCM,data:XevJPA==,iv:0+lKp98yvSUGhtWnd4KHneoP5qV1uIjPzGY9e3KqYXY=,tag:5+GjxpnRtImV/2GWV6ugKw==,type:bool]
    skip_qb_version_check: ENC[AES256_GCM,data:rSU9DaA=,iv:m3m6sSeC9JrEb1N8ls+aufTUlDQ+P63J713fcVFjGE8=,tag:T6smdK7ojzn+26jhjUZqNw==,type:bool]
    skip_cleanup: ENC[AES256_GCM,data:cXyBsy0=,iv:W3ka0bzoMrnueIpT0cPKWTszRH8+EUw9b4hEtgd5WHI=,tag:EqmzI7LM2Q6SJRTGqCWf7g==,type:bool]
qbt:
    host: ENC[AES256_GCM,data:6YL4BsIZyrcN,iv:65V6tW6i8OgPxoe2gV9kNUkh5K6tdugYnYOvqDS14sc=,tag:+xWT9RGTg/hb5XEiXeaP2g==,type:str]
    user: ENC[AES256_GCM,data:4ZdGTyUlKw==,iv:kDogAdJKA9HAw1VWqDMwMyWQSIXTYyyv75NRt9Vh6nY=,tag:HI9GRd8fHqN+reEgRa6/bQ==,type:str]
    pass: ENC[AES256_GCM,data:TFIhzYTyDVAE,iv:g+SEwVMEdIFkmv+VqxnjFKGrC7/Jn3pmBSSDThVlnrE=,tag:0HG4VoqH+jeE9BffeOJCQg==,type:str]
settings:
    force_auto_tmm: ENC[AES256_GCM,data:gqXw1w==,iv:+sA5uKt65rl+mV8x0EIbJhL5S7ULFMtsGFuK2Qt33QA=,tag:3XXWznCLqNSsRCQyZ6N/mA==,type:bool]
    #ENC[AES256_GCM,data:pZ3UT6ybeO1ziZkj+/4uHLhDNpBLkrMl8w==,iv:vhbEpaK/W4boFDVdFWzjNq2EFceMsDmuOq5iWj8oHOM=,tag:PYqXgXz+b25DDDr2hN9MHg==,type:comment]
    nohardlinks_tag: ENC[AES256_GCM,data:LZNvZg==,iv:xzLzKU8eBmsVO5nOMp2SDShhX4alOmHmjzDFHKK4yFM=,tag:tUOOs6sBj3wA7JFyCptSdg==,type:str]
    share_limits_tag: ENC[AES256_GCM,data:GaM235YHPvFBBx81,iv:hSlAzsGM8dtSqGVvpLfQGniEl3m8LTwYsikm8XEDJR4=,tag:osUJfjptKBxb8a8If7AgJw==,type:str]
    ignoreTags_OnUpdate:
        - ENC[AES256_GCM,data:9aKCfQ==,iv:V8B6WaRyLAMGpQfHkypAcW3ei7bdtL4r70cbQUgdMHo=,tag:+SSalQ78GBsViCaZLqbSdg==,type:str]
        - ENC[AES256_GCM,data:mvALB/0=,iv:SBQ1KApkP4f3nVL/dhUBiCpEy/iALS0r/5GoiBt7Q/U=,tag:bibc3LzlnYWM4SK/Mx81fA==,type:str]
        - ENC[AES256_GCM,data:Ee9B/Uj0OxSwIQ==,iv:20U/d0kMtJUG0gC9hZpKx8KFUNADbPD5x26asJ2Bs6w=,tag:yZQsPDwX5/AzezZwX5jZow==,type:str]
    tracker_error_tag: ENC[AES256_GCM,data:V99N86E=,iv:/h2eq+kNRqQUsSEfWHPvAfqkJGo1XqOQ3S0x/LoeunQ=,tag:QQKeEVCCSz4MM6JWWXy0GQ==,type:str]
    share_limits_min_seeding_time_tag: ENC[AES256_GCM,data:CujyX/gyrZXz0sbfxQ06YaMu+h4H,iv:q815BgU30kDLtwi0Lotto68ejYvE7DCLzcrMq8spZF4=,tag:dGgj/Pf5/M4WmzJKci6bNA==,type:str]
    share_limits_min_num_seeds_tag: ENC[AES256_GCM,data:quUq15jyxjg0B5HXOzs=,iv:Gb7Lg/TJgFidUjAUkiXhB9rNwe0JbxkiKVP0aFgjU+o=,tag:2CITi10oSnn6a2ITW07oUA==,type:str]
    share_limits_last_active_tag: ENC[AES256_GCM,data:7/SPaiKew6wnnuVMxYzpI4Mz+qGoBoAwSQ==,iv:ClPxs5Lyr89cGPYYK8YyNIAHBmJv/BMOIW+fTHjFcgc=,tag:yH+Hhq64LRDEQyZwbvWsUA==,type:str]
    cross_seed_tag: ENC[AES256_GCM,data:qjAZmyTZdoBjzw==,iv:0kZ+On/SbOBY2017yJuQXw5qIcBVMeavERBka7UumVQ=,tag:TlZrstdV30GbBDvUi0GO+A==,type:str]
    cat_filter_completed: ENC[AES256_GCM,data:o7ez1w==,iv:08NBEkaQ0HAaH02gfv6PubGs3qoHHISTYcHINehhbT4=,tag:ihWYZoWgEZzLOzJRuhsmtQ==,type:bool]
    share_limits_filter_completed: ENC[AES256_GCM,data:1DX5Kw==,iv:HTk6PDJqciV+NScOBGraOvOXVEQSpNoPyEd9iP1GwRA=,tag:KnIsVA44erkf2fVOSKa9rw==,type:bool]
    tag_nohardlinks_filter_completed: ENC[AES256_GCM,data:v7JT3w==,iv:byAdAVm6u5mtrz1FtKH99+rNB0hGhP6ZqRk7yAMvsEI=,tag:G3fj+tXsViyQB9dC7fRupg==,type:bool]
    cat_update_all: ENC[AES256_GCM,data:uB3zHA==,iv:dhzQpRjYEbK9S+7VJubYCk9YXJaiR9XDUxLYRNRwr9w=,tag:DoEQ7Rg5XS7UqRWebhFxdw==,type:bool]
directory:
    cross_seed: ENC[AES256_GCM,data:huh6nCP94BJLF7CEhCYi0YOb6JXmVWtJZFKpsFYZNmvt559p,iv:aJG8duW8wpCokCqdlSbMm4KKE4941uFJRNWFC3cDgVk=,tag:K8ejqRIv53DWuwR4kuMElg==,type:str]
    root_dir: ENC[AES256_GCM,data:cj0PUF/KJBL8mpsFR4rPsQTOs7vr3rYFfA==,iv:RPujjyXjhOqinIr6UhgkjLAtyiCK4SL+ZaE5+CFhZnA=,tag:O/yGhTzh2udBBHG8lSZkkw==,type:str]
    remote_dir: ENC[AES256_GCM,data:AaC9Ljy1lAFMTjGcJgXjIJI9/oumQ2aYIg==,iv:0x5F8noAnWl8QdKPHEQIvOrI3WBAXYzA4lzkOVmFms8=,tag:6zduj6AthsvAJkEUAiFopw==,type:str]
    recycle_bin: ENC[AES256_GCM,data:tH1/HdQPptoxIcXpdNykOm2SZAP/8V+2pzmxImGksITJqWEf,iv:DR4rRCJld0x2ilSq5XCGgJ9OQlLkrvcp0hYT5skD+4c=,tag:lPU31S0zZ9j6MW5Vnf5MDg==,type:str]
    torrents_dir: ENC[AES256_GCM,data:iGWQY3gkMc1Zhnb3Wfv2yo3k/6RXHx0jFVwnhhLLYwWLfA==,iv:/G4Ugp7uaB7IdHrw1PsIpFpnk667Ive3PXTq78wgNEc=,tag:yZ64HchQmAw6yr+XRpKBPw==,type:str]
    orphaned_dir: ENC[AES256_GCM,data:XnwYPHxozfHbJI4SZB/bSFrH5/cZDW95VsDIuHJ8fZo7knvGFFg=,iv:n5CxTPPuQL+qVKDgRdhI85C01doHWe4y5rGxImUwpWc=,tag:m8esvAKqInbuQuOTpQAkZA==,type:str]
cat:
    prowlarr: ENC[AES256_GCM,data:WM5gPo3++uG7iOSZd/q3+Au0DniOyepzKzw=,iv:lArmrfu4eyV0of84v0K0bS4ITs3Tt8jmYJkYDG12+co=,tag:aIw8+BsS5aHflnP8MiE1hQ==,type:str]
    radarr: ENC[AES256_GCM,data:Y9Qw0hg/VFcI0k0CUuVR/kEOr63ZNjt5,iv:d+xqzs284hHWbcIMT6xhWp9ERWWSL8u7QyVrQ4B2nGI=,tag:8kM3bdNCAgavwb6T2Z9/Yg==,type:str]
    sonarr: ENC[AES256_GCM,data:5aweA/NYwDDbBjlrVgocHpre92c7ygI8,iv:iYt/VgcbOql9Dwn9rkx2nKbNUEQj0jR0sHFfH02ZBFg=,tag:nFc1Ba5eoZfv8jd5UXIBgQ==,type:str]
tracker:
    nyaa:
        tag: ENC[AES256_GCM,data:Cc6cvQ==,iv:g5XKxHLP/etNtkiegjG8H1I17IYlsoRjJbhN1oIzpV0=,tag:SgsCaSrSU4WYGxi+D9nppQ==,type:str]
nohardlinks:
    - radarr:
        exclude_tags:
            - ENC[AES256_GCM,data:bDDAig==,iv:iNdi9ZM+fK8rdSkugsnjCee0fiiebkNNWorpIUEN9uc=,tag:8FvlylmjDR+D/MjNQNoDRQ==,type:str]
    - sonarr:
        exclude_tags:
            - ENC[AES256_GCM,data:B2owNA==,iv:cS3hgRqtoV2xEEGhXZb5f9PZ/chHpPd/J/djgpNvsmc=,tag:YdFkyN+wvtoGMb+WCSJTwQ==,type:str]
    - prowlarr:
        exclude_tags:
            - ENC[AES256_GCM,data:s/+k1g==,iv:tijJKsNzBVz29qM+gcMs/eSpm34kO19sllsxK4wurPU=,tag:/rrA+F7+Wh+O0SMe02BJfQ==,type:str]
share_limits:
    keep:
        priority: ENC[AES256_GCM,data:1A==,iv:leyIxnnYh6H9S31osHXY/AdA3qyGhn5Go9hl2uU3uyA=,tag:MhxPFGff8WHyiRWTAcE3Zw==,type:int]
        include_any_tags:
            - ENC[AES256_GCM,data:pLFCeQ==,iv:mGRLFFyGYUWFaE/mS3MdQVu1v3RlCsrcT7nGOBOydeY=,tag:SKCe6DGY2ilqx7WCAo+ubQ==,type:str]
        max_ratio: ENC[AES256_GCM,data:C8g=,iv:znpwdQS3DPqp1Q7js8l/X9ftazfzoluVBUuXt4pqzE8=,tag:rTnXen7rQvgdm2EobvEsIw==,type:int]
        max_seeding_time: ENC[AES256_GCM,data:izg=,iv:tDc8kSSBYdQI6LloFlNcy/B9/XMVCczZ6Wg35WRICmU=,tag:rpAemTb/RZ5CJ24qClqyCQ==,type:int]
        last_active: ENC[AES256_GCM,data:UA==,iv:wL3aFLugNxzhlGxU9entIzvOUSnIAvqxQyjMKY77hmE=,tag:2jP5Pql/P/ps3mzRr3QQfg==,type:int]
        limit_upload_speed: ENC[AES256_GCM,data:cQ==,iv:0L7gBxptOxZOZNq7c6379EfOKo8f7PavQhmv3nyim30=,tag:kUJHH2T3ntEBg51lANSZ/Q==,type:int]
        cleanup: ENC[AES256_GCM,data:wjKKVsY=,iv:0SlgdUyxWKmU1zTQhm1HKVIKOeFl7/mdQfcWjvp/Uzg=,tag:V2XG5jADvb4jJNlljNTdvg==,type:bool]
        resume_torrent_after_change: ENC[AES256_GCM,data:fPsVSA==,iv:xLn7m+9sVOfr1QWETWBVkxs1Do32mA32gzPmIbBSRB0=,tag:5ksSxznPpIPK2OmonfQLPg==,type:bool]
        add_group_to_tag: ENC[AES256_GCM,data:xhNu2A==,iv:nXqn5K2sb2a9HyLlYAqdifqVwLruBwRp7LoSvRbHmfI=,tag:AunbSZN8Dd4yBBfEc6eWfQ==,type:bool]
        min_num_seeds: ENC[AES256_GCM,data:qg==,iv:2/ud+eBwr7sWROFHm2DoFAfpqcjbACKDf0623jtl4Hs=,tag:AjxqSjcCTNn0J2RUDa33gA==,type:int]
    legacy:
        priority: ENC[AES256_GCM,data:5A==,iv:5vgSScY2hnD+7UZMtz/dq5VN891ZCb3v85BBXL1WnIQ=,tag:XrjmH2Po9q8sjW6bpwaacA==,type:int]
        include_any_tags:
            - ENC[AES256_GCM,data:cRrBWA==,iv:3QXbEYrYKFIIbjnGzjKe6/HmTcvUcJdRe71tkAl1ULA=,tag:udUF95I4Ht27Svfhyls6XA==,type:str]
        max_ratio: ENC[AES256_GCM,data:bQ==,iv:bEeR4DHdUSzAPFQg/TbUUGrHnehNTo76RmY0od5VVF0=,tag:48IXmaSH/o75CdHwwjuwBA==,type:int]
        min_seeding_time: ENC[AES256_GCM,data:XBHMQOv29TE=,iv:v4UMJOmTfMcLKCbk8jWS3PaA3OgAWIO61jq0oneKMTM=,tag:xTOSjgo44fgCpZa3WBo2NQ==,type:str]
        last_active: ENC[AES256_GCM,data:xPU=,iv:FeZHmnpxmJxFo7HcC5OCv1EcLnNs0/XVIBvh3JIu7m0=,tag:qgwCMYcI9GInhJYRh+VPGQ==,type:str]
        cleanup: ENC[AES256_GCM,data:oUnQYg==,iv:dUKu5Fz8B2UNGyby8q7V4v9wlEbdKVm+u4v2t9B2TjM=,tag:JdcooJM327KIYAHX2GSpQA==,type:bool]
        resume_torrent_after_change: ENC[AES256_GCM,data:qjZoBA==,iv:9FJ2OPHziaDE8s2l0ZRboXqMGp9BpAZS1oV3qgspz+o=,tag:s9Q9UYJr7I6vyMzafk9kcg==,type:bool]
        add_group_to_tag: ENC[AES256_GCM,data:F+qjUA==,iv:F+OU5XJ1zw/Y3Eh0p7GGZxsGxiwu83VY1NZLz3cR16E=,tag:3Ki6nYXngnb10v5Nl0Qdsg==,type:bool]
        min_num_seeds: ENC[AES256_GCM,data:rig=,iv:GSicGw8vs5/OtFpPm0OTe5F7O6XTWErQ8RRoFMUPkQY=,tag:VlxDKFFm0wp2w993jwV87g==,type:int]
    active:
        priority: ENC[AES256_GCM,data:FQ==,iv:Co01GMAYRRq21eppUMXcuoGjOAt+7kv5+S2QaQaiSoc=,tag:Yzn+8RO4c29QRl93FwSQeQ==,type:int]
        max_ratio: ENC[AES256_GCM,data:Jck=,iv:oNyovY8tbP02AV5CHZSuibGBurp2M5llN8C36d+IbOM=,tag:+mLevBQ7R1CJ+jnrwQzdEg==,type:int]
        min_seeding_time: ENC[AES256_GCM,data:8Q==,iv:vT7g1OdMOqsU7iHN4xn4SzmyAJWzu6shmLPfVgsOMdA=,tag:2FCj8meiLrFu6fPG1WnKkA==,type:int]
        last_active: ENC[AES256_GCM,data:2g==,iv:jzl+HH6zpwxCKvF5IFOyYsgW+p+dWkYqS3RV8ZTsrDI=,tag:y/pMn9Wh0QQ3i8pD1tm9sg==,type:int]
        cleanup: ENC[AES256_GCM,data:yPMc0dc=,iv:AL+KW+0/fzxdni5BjpPSPB+nTDH9dR2vMym8lJ5X/JU=,tag:wDji/pUw3hJyAM7yW6Y2Aw==,type:bool]
        resume_torrent_after_change: ENC[AES256_GCM,data:IJvZRw==,iv:yi8bGJAdBmm3r4Ou3BuuI6t030JBnKD4E8xRxbxhpeQ=,tag:V8AusPX5CXBBIeKbekUZ1Q==,type:bool]
        add_group_to_tag: ENC[AES256_GCM,data:Luup6Q==,iv:zl4VlOQB7iie5bpnTFkUjlYraNeSZf+ETlgSVCPQJUE=,tag:R1CDN5xambC6jSfIwgNLjw==,type:bool]
        min_num_seeds: ENC[AES256_GCM,data:7A==,iv:6BN0wPerX7f7ZbEQ4XyiguuGm73yGyCxILX0cPF+css=,tag:d40U3+sI2fif4pcuR1X3/g==,type:int]
recyclebin:
    enabled: ENC[AES256_GCM,data:bhOXRA==,iv:CUHcUjVqe335UBLq0EPs+HbDKyTcjMYEr+BuZpXJbDY=,tag:2EXS+in7cT0gVovaE0WCsw==,type:bool]
    empty_after_x_days: ENC[AES256_GCM,data:/rs=,iv:nY+cN0lQeJfTpJHwmJ0Kseslu9Y99hII581NjLmBzLg=,tag:ueCjMmik5YIiC8l6vp9TOw==,type:int]
    save_torrents: ENC[AES256_GCM,data:dFib2js=,iv:fr5vfgDaKYw+3sA7T16z9Q+wg81u/1gdU0ms8q9cCEo=,tag:DAlsIO9hvtAL0TfI3Xy2+A==,type:bool]
    split_by_category: ENC[AES256_GCM,data:iBNEtg==,iv:zev5MY1i7+XmCGvvegrNQVGiJetJzYl994oqHpII8zA=,tag:ZFtnAZHBM3mym3sX9INz0A==,type:bool]
orphaned:
    empty_after_x_days: ENC[AES256_GCM,data:o40=,iv:m0zTRosNFdXZ7TrhRSK9Cp8IdtOdvG5UNgoFja2oFQQ=,tag:VNL86y67jsKbOpEoIRbOVg==,type:int]
    exclude_patterns:
        - ENC[AES256_GCM,data:tyLnX4m1RdmfBdSQ,iv:YiH7hyBY2ScZX5Lc06B8pSbwxFYCa2wzHTVeCjHBfmY=,tag:mrSBs41SHpr+wuwOaMxSVw==,type:str]
        - ENC[AES256_GCM,data:i3m5MGRPgS2BfR0W,iv:V2wtDKSXCmVZ+oJfLg5Yd/TbvSOIxY2sSIExuB88SWI=,tag:Styk8sYK6Id+IpBycKXSeA==,type:str]
        - ENC[AES256_GCM,data:VqSgnABqN1wT,iv:iATwPEbyw4gZTqYW6k62V31gHF0tXKAhw+NykgqskpY=,tag:cdnn7Lc3HTJnFJezXBHrRA==,type:str]
        - ENC[AES256_GCM,data:qxUdZAe1JnIHnsx0XqGaCL+s6igGqg==,iv:DFjFNJIRM/wLBwNy3TzOoBvk5b3GUInfW7e/MXXl/YI=,tag:UyuLS1YPcBFkM2MXUyJaHA==,type:str]
        - ENC[AES256_GCM,data:Al0qY8x0P/4=,iv:QyTaNOpUVfkFskd+g79e7TCTYVyhJZC1goxtlkaGrI0=,tag:eDul0PkMeaL9Li8UEhtbZg==,type:str]
        - ENC[AES256_GCM,data:1e3qUxZGAkIErfAvvhs6cg==,iv:nxr0ayavlfj8oJW042m/KFSvzZAPenjFyUdc9d+89lk=,tag:8MYxyi828bt7Ud0LOASY3Q==,type:str]
webhooks:
    error: null
    run_start: null
    run_end: null
    function:
        cross_seed: null
        recheck: null
        cat_update: null
        tag_update: null
        rem_unregistered: null
        tag_tracker_error: null
        rem_orphaned: null
        tag_nohardlinks: null
        share_limits: null
        cleanup_dirs: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1chvcefkzfesskrs2vf7sp9fjktpx5z8qc4ggksuwfn483fwpjvxsv88jpa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMmdwOG94ZzVWaDk5d3RQ
            c0I3OGFNL0IzbVJsNGFhc0NRdUMwUWVtWkE0CmZXdHdjcnpnaHBnMm0wME55NWRy
            bG9NQm5hU2RtTEJWeHRHRzIra2ZRT2MKLS0tIGpuZDNJa3lpQW53dCtiUnNleDdK
            WkJMMExYdDNoRW1iT1dkYXJXSm9LSFEKFCPZRJzMFjWe7HeKh0S4abRl7ubeYx0+
            Sj3khqoKweaqRTAa5y3XtUhO3dNpZQ3sjLEH23uBQTbwAbOyC11Lyw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tsfvlywtu7c9aux8y9efscqak3nvmz85zanyv5q2qvwthphf5u7qa499tl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dzVzbUtIdWpNUi8vV2dI
            NWJSRGJFTVVyMWN3V2RjNzJ5dTNpNk9pQkVrClhBaitNeVF2Q2g5YjhlZUErTjVh
            T05VZ1IySXgwbHgwcDkrOERZMHhFMlUKLS0tIDZvUzYraUtqSUxadjFUWU5CZHFy
            amppT0EwdmpwNkFoTUV1Q2JDdkg2Sk0KsUs2HuBKo+dwNxvJNIBEJxnREYwMzKyn
            qtgRD9Z82zDqvv/V0CB6L+XlL49XvLQuNJknbEM4aYAyzB+D6TA4NA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mslxutmqu56fhl0rgk7flysyacyxks3evnmfckzzykh3wcvzc5tqx9q6dd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpb3djUDVkM3FCMlZucXdO
            TG1RVXpvdWdVanlhK25HM3cxZGhRNm1UUEMwCmQ5QS9zd0llenBzN0RMWFVscit5
            TDN4Z2VFNzVENks1MEdMbThCS2l3aVkKLS0tIDgxcW04aUVGS3NoeHBBNWdVK2s3
            emFWNVlvU1orSzhqWXorbW5zaVk1QzQKt6/ceglNHEjwJA0LISd0GioFKf+vhS+G
            WZjVq7lOpjKR8LhU78/SMpgTBRkrOfBgFJ5ZTgUAXLoQACrk9Fkv+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x3tjqh5n09yzmtlgdw7gxdavpxqtktvgavf4gdv6mw5qcq49uypqq34rqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbXI1ZVFJYUVpZFFsall3
            aTdxc2xKbkNhQUVxTEZlYlV5eTZIUjMyWXprClp5eVM2dEZ1dFN3V05UUWF6K3NB
            M3hlVVVEZEhaYWtiZVd5R0RJTGplOXMKLS0tIHQvZCtlQ2NYRVFLaXJMb055ZzBI
            QzRpNWU1eUFXblhOTXlEL0NnUFJ0bGsKOsCbOufTiEBuSq1Ok8GJ3VnHW3uSB9KQ
            fGsX87YvdAdHm0z9pkjknoGHsPR7uqm0BUmOZsgVkbOaRxUINQaZjg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lz59a9hcx9wfknc2p4lv9hej4exjqawsx04g82e8d7e8fkhqegkqpmegu9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzS2ltTGM5NktNVFU0Wi8y
            MHErTXJHUmhmbWJOUEFlcForSERsb0lmbUc4CkRON2w1U0FYQWlUeGRrVG8yRUh1
            b0hKUkQyY1FtYlJ5cjgrM3lOMVVucUkKLS0tIFVOcCtReVFYRjBrcFhDbTJMTTVZ
            cFprVmhyZzJqeWg3cGN1T3BFYXpHelEKmTS1WPPXV7xT6Bi4djUfs8Me12O8srS2
            WCJ+ZMR+2NGstdFyKE06P/b1L+ljOCe4Cba6InVIqFAML1slmgl3ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-09T19:54:19Z"
    mac: ENC[AES256_GCM,data:aEuX01/6C7wb9bSBku4V61o98C91RQk6BSk0f7hdzgR86v1EvXRWjkuMzMrjSXDFNOipfXWv2r+vIzZFYsEfwA7/Z0L3V+YhBt8DlkISj97Ea69v2Z8aFdvdjrqvGuGjNXHK87/WM8fbbWhw6UOUR7WaoDcCsHQVyd/SmQKGLh4=,iv:JxUyO0sWNknAMSO6BzdtpTwuE7Ihtgej8CxTvPRiXSM=,tag:lvAkSKp8M+JXj8zG5bvQkQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
