{ self, ... }:
{
  flake.homeModules.k8s-cluster-administration =
    { pkgs, ... }:
    {
      imports = [ self.homeModules.kubectl ];

      home.packages = with pkgs; [
        k9s
      ];

      programs.kubectl = {
        enable = true;
        settings = {
          apiVersion = "v1";
          kind = "Config";
          current-context = "default";
          clusters = [
            {
              cluster = {
                certificate-authority-data = "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTnpRMk5EYzBNVGN3SGhjTk1qWXdNekkzTWpFek5qVTNXaGNOTXpZd016STBNakV6TmpVMwpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTnpRMk5EYzBNVGN3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUOXBLVmFyWllmYWU2NWt2WjRkOVJKaGdSd3U2K0U0Y2wxZWpuMWFiSGQKVkZkeWpKZGFhNWVjYmw2S21GU3N4aCs1d2c5dmxhSTJyWVpiWHNpTG9lR1JvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXphTitEb1Zxd09wUmw0eEM2WERMCmVnYXhsNkF3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnYjkyTmI4KzlxU1VvazhUNkFBM1V1MDlDaHBtQS9US0gKNFdVRmF4QXRZUmNDSUFreUlsZEptYmpzT2pselI3V055VVJFdUppVjZNU1dteEJIWG5MSlMxYUMKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=";
                server = "https://andromeda:6443";
              };
              name = "default";
            }
          ];
          contexts = [
            {
              context = {
                cluster = "default";
                user = "default";
              };
              name = "default";
            }
          ];
          users = [
            {
              name = "default";
              user = {
                client-certificate-data = "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrRENDQVRlZ0F3SUJBZ0lJVWQ1bXMwbkdEKzh3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOemMwTmpRM05ERTNNQjRYRFRJMk1ETXlOekl4TXpZMU4xb1hEVEkzTURNeQpOekl4TXpZMU4xb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJPb1dqYm1mZCtpRDZ4S1kKVUxDWUV4aTUxY0pJM09LekxTcjU0Q29mNm9jU3FtRCs5bG1RRWZkMHdtRllLU01qV0JNMXhiUUxlZ29KR2NjbgpTS1hMRTVDalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCVGlTVFdrQ2lJTldXbjBIN05HMEd1czVGT3lsekFLQmdncWhrak9QUVFEQWdOSEFEQkUKQWlCU25lbGErd3NJOXpRUVlKYXRkSGF1bXYwdzR5aE01OTVUNUp4QndxeDlaZ0lnTEZXZklXTkpkc0ZWZkVZeAoxbGJXZ05jeGVhb0lpT1RkeFV2TlNOYm55VVU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzTnpRMk5EYzBNVGN3SGhjTk1qWXdNekkzTWpFek5qVTNXaGNOTXpZd016STBNakV6TmpVMwpXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzTnpRMk5EYzBNVGN3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSV01heFFtRmxrcjRSdUFJRU1QWWszWUtWcG5IVlhlV0R0QWU1REpEMFUKRXFjQ2VkTmlpbDhrd3hpSG95RTZKTDZhVmV6RTA2RWZ0L01ldDlUZTEySlJvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVTRrazFwQW9pRFZscDlCK3pSdEJyCnJPUlRzcGN3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU8zR3BiMzNhQkZqS0RVODBTWGFXR3gza1VxeElhUlgKdWhVeHRLemJ0aXNyQWlCODl0WStXNWtCWDkwR3pmb2dNOTB0enZQRStCZ09kU0VjcmtHaU9RU3ZzUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K";
                client-key-data = "LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUpUcFZpbXJKNlBnRUk2b0srOG1PSStXckdLdWdZNTdqN254dVZPdVJ6bzFvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFNmhhTnVaOTM2SVByRXBoUXNKZ1RHTG5Wd2tqYzRyTXRLdm5nS2gvcWh4S3FZUDcyV1pBUgo5M1RDWVZncEl5TllFelhGdEF0NkNna1p4eWRJcGNzVGtBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=";
              };
            }
          ];
        };
      };
    };
}
