name: Build and Cache Flakes

on:
  # Run on pushes to the main branch
  push:
    branches:
      - main
      - refactor/*
  # Allow manual triggering from the GitHub UI
  workflow_dispatch:
  # Run on a schedule (e.g., daily at 06:00 UTC)
  schedule:
   - cron: '0 6 * * *'

jobs:
  # A separate job to handle updating the flake.lock file
  update-lock-file:
    runs-on: ubuntu-latest
    # Grant permissions for this job to create a pull request
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3
      - name: Update flake lock
        uses: DeterminateSystems/update-flake-lock@v27
        with:
          # You can customize the commit message for the lock file update
          commit-msg: "chore(deps): update flake.lock"
          pr-title: "chore(deps): update flake.lock"
          pr-body: "Automated dependency update via GitHub Actions."

